#!/usr/bin/env bash

ts_flags='--alwaysStrict --strictBindCallApply --strictFunctionTypes --target ES2024'
js_flags='--harmony'

set -e

file=$(realpath --relative-to="$1" "$2")

printf "START [$(date '+%Y/%m/%d %H:%M:%S')]\n"
trap 'printf "\nEND [$(date '\''+%Y/%m/%d %H:%M:%S'\'')]\n\n"' 0

printf "\n+ npx npx tsc \$ts_flags $file.ts\n\n"
time npx npx tsc $ts_flags "$file.ts"

printf "\n+ node \$js_flags $file.js\n\n"
time node $js_flags "$file.js"
